global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: kong
    metrics_path: /metrics
    static_configs:
      - targets:
          - kong:8001

  - job_name: patitomedi-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - user-service:8080
          - appointments-service:8080
          - payments-service:8080
          - medical-history-service:8080
          - video-call-service:8080
